import type * as A from '../ast/nodes.js';
import { collectBuiltinNamespaces } from './helpers.js';

/** Plans deterministic Runtime and standard-library imports for one emitted module. */
export function runtimeImportLines(module: A.ModuleNode): readonly string[] {
	const lines: string[] = [];
	lines.push("import { Err, None, Ok, Some, checkForeignBigInt, checkForeignBool, checkForeignFloat, checkForeignString, debugValue, decodeJsonValue, defensiveCopy, byteCreate, bytesConcat, bytesEmpty, bytesFromBase64, bytesFromHex, bytesFromUtf8, bytesGet, bytesLength, bytesReadInt32, bytesSet, bytesSlice, bytesToBase64, bytesToHex, bytesToUtf8, bytesWriteInt32, mutableBytesCreate, mutableBytesFill, mutableBytesFromBytes, mutableBytesGet, mutableBytesLength, mutableBytesSet, mutableBytesToBytes, durationHours, durationMilliseconds, durationMinutes, durationSeconds, durationToMilliseconds, encodeFfiValue, encodeJsonValue, floatToInt, int16Create, int16ToInt, int32Create, int32ToInt, int64Create, int64ToBigInt, int8Create, int8ToInt, intAdd, intDivide, intMultiply, intNegate, intRemainder, intSubtract, isPropagation, listAll, listAny, listAppend, listConcat, listDrop, listEnumerate, listFilter, listFind, listFirst, listFlatMap, listFold, listGet, listIsEmpty, listIsNotEmpty, listLast, listLength, listMap, listPrepend, listReverse, listTake, listUnique, listUniqueBy, listZip, makeRecord, makeVariant, mapEmpty, mapEntries, mapGet, mapHas, mapKeys, mapMapValues, mapMerge, mapRemove, mapSet, mapSize, mapValues, optionAndThen, optionCollect, optionFilter, optionMap, optionToResult, optionUnwrapOr, panic, parallel, parallelTry, parseJson, propagate, queueDequeue, queueEmpty, queueEnqueue, resultAndThen, resultCollect, resultCollectErrors, resultMap, resultMapError, resultOrElse, resultToOption, resultUnwrapOr, rootTaskContext, runDefers, runDefersAsync, safeCall, safeCallAsync, setAdd, setDifference, setEmpty, setFrom, setHas, setIntersection, setRemove, setSize, setToList, setUnion, stackEmpty, stackPop, stackPush, streamCollect, streamFilter, streamFromList, streamMap, streamTake, stringAt, stringCodePoints, stringContains, stringGraphemeLength, stringGraphemes, stringEndsWith, stringIsEmpty, stringIsNotEmpty, stringJoin, stringNormalizeNfc, stringNormalizeNfd, stringNormalizeNfkc, stringNormalizeNfkd, stringLength, stringReplace, stringSlice, stringSplit, stringStartsWith, stringToLowerCase, stringToUpperCase, stringTrim, stringTrimEnd, stringTrimStart, taskFirstOkBuiltin, taskMapParallelBuiltin, taskRaceBuiltin, taskRetryBuiltin, taskSleepBuiltin, taskSuperviseBuiltin, taskTimeoutBuiltin, uint16Create, uint16ToInt, uint32Create, uint32ToInt, uint64Create, uint64ToBigInt, uint8Create, uint8ToInt, updateRecord, valid, invalid, validationAndThen, validationCollect, validationMap, validateFfiValue, viruneEquals } from '@virune/runtime/v2/index.js';");
	const builtins = collectBuiltinNamespaces(module);
	if (builtins.has('File')) lines.push("import { closeHandle as $fileClose, openHandle as $fileOpen, readBytes as $fileReadBytes, readHandle as $fileRead, readHandleBytes as $fileReadHandleBytes, readText as $fileReadText, writeBytes as $fileWriteBytes, writeHandle as $fileWrite, writeHandleBytes as $fileWriteHandleBytes, writeText as $fileWriteText } from '@virune/stdlib/node/fs';");
	if (builtins.has('Path')) lines.push("import { basename as $pathBasename, dirname as $pathDirname, extname as $pathExtname, isAbsolute as $pathIsAbsolute, joinParts as $pathJoin, normalize as $pathNormalize, relative as $pathRelative, resolveParts as $pathResolve } from '@virune/stdlib/node/path';");
	if (builtins.has('Process')) lines.push("import { architecture as $processArchitecture, args as $processArgs, cwd as $processCwd, environment as $processEnvironment, exitCode as $processExitCode, platform as $processPlatform } from '@virune/stdlib/node/process';");
	if (builtins.has('Http')) lines.push("import { get as $httpGet, request as $httpRequest } from '@virune/stdlib/node/http';");
	if (builtins.has('Fetch')) lines.push("import { get as $fetchGet, request as $fetchRequest } from '@virune/stdlib/browser/fetch';");
	if (builtins.has('Timer')) lines.push("import { now as $timerNow, sleep as $timerSleep } from '@virune/stdlib/timer';");
	if (builtins.has('Storage')) lines.push("import { clear as $storageClear, get as $storageGet, remove as $storageRemove, set as $storageSet } from '@virune/stdlib/browser/storage';");
	if (builtins.has('Dom')) lines.push("import { addClass as $domAddClass, getText as $domGetText, setAttribute as $domSetAttribute, setText as $domSetText } from '@virune/stdlib/browser/dom';");
	if (builtins.has('Crypto')) lines.push("import { randomUuid as $cryptoRandomUuid } from '@virune/stdlib/node/crypto';");
	if (builtins.has('Url')) lines.push("import { decodeComponent as $urlDecodeComponent, encodeComponent as $urlEncodeComponent, isValid as $urlIsValid } from '@virune/stdlib/url';");
	if (module.declarations.some(item => item.kind === 'TestDeclaration')) lines.push("import test from 'node:test';");
	lines.push('');
	return lines;
}
