import assert from 'node:assert/strict';
import test from 'node:test';
import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { BASE_RUNTIME_IMPORT_LINE } from '../src/codegen/runtime-imports.js';
import { buildProject } from '../src/project/project.js';

const execFileAsync = promisify(execFile);
const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');
const mvpRoot = join(repositoryRoot, 'selfhost', 'mvp');
const temporaryRoot = join(repositoryRoot, '.test-tmp');
const SELFHOST_RUNTIME_IMPORT_LINE = "import { intAdd, intDivide, intMultiply, intNegate, intRemainder, intSubtract, isPropagation, propagate, rootTaskContext, viruneEquals } from '@virune/runtime/v2/index.js';";

type ViruneResult<T> = { readonly $tag: 'Ok' | 'Err'; readonly $values: readonly [T] };
type EmitterApi = {
	readonly emitProjectJson: (request: string) => ViruneResult<string>;
};
type EmitterResult = {
	readonly accepted: boolean;
	readonly entryPath: string;
	readonly emittedModules: readonly {
		readonly sourcePath: string;
		readonly outputPath: string;
		readonly code: string;
		readonly sourceMap: string;
	}[];
	readonly dependencies: readonly unknown[];
	readonly exportedSymbols: readonly unknown[];
	readonly diagnostics: readonly {
		readonly code: string;
		readonly message: string;
		readonly sourcePath: string | null;
		readonly outputPath: string | null;
	}[];
};

test('project emitter canonicalizes modules and metadata independently of request order', async () => {
	const loaded = await loadEmitter();
	try {
		const request = {
			entryPath: 'src/main.virune',
			modules: [
				{
					sourcePath: 'src/main.virune',
					outputPath: 'dist/main.js',
					preamble: ['import { value } from "./helper.js";'],
					statements: ['export function main() {', '\treturn value;', '}'],
					sourceMap: '',
				},
				{
					sourcePath: 'src/helper.virune',
					outputPath: 'dist/helper.js',
					preamble: [],
					statements: ['export const value = 1;'],
					sourceMap: '',
				},
			],
			dependencies: [
				{
					modulePath: 'src/main.virune',
					sourceKind: 'virune',
					specifier: './helper.virune',
					resolvedPath: 'src/helper.virune',
					typeOnly: false,
					public: false,
				},
				{
					modulePath: 'src/helper.virune',
					sourceKind: 'javascript',
					specifier: 'node:process',
					resolvedPath: null,
					typeOnly: false,
					public: false,
				},
			],
			exportedSymbols: [
				{ modulePath: 'src/main.virune', name: 'main', declarationKind: 'FunctionDeclaration' },
				{ modulePath: 'src/helper.virune', name: 'value', declarationKind: 'TopLevelValueDeclaration' },
			],
		};
		const first = emit(loaded.module, request);
		const reordered = emit(loaded.module, {
			...request,
			modules: [...request.modules].reverse(),
			dependencies: [...request.dependencies].reverse(),
			exportedSymbols: [...request.exportedSymbols].reverse(),
		});
		assert.deepEqual(first, reordered);
		assert.equal(first.accepted, true);
		assert.deepEqual(first.diagnostics, []);
		assert.deepEqual(
			first.emittedModules.map(item => item.sourcePath),
			['src/helper.virune', 'src/main.virune'],
		);
		assert.equal(
			first.emittedModules[1]?.code,
			[
				'import { value } from "./helper.js";',
				'',
				'export function main() {',
				'\treturn value;',
				'}',
				'',
			].join('\n'),
		);
		assert.deepEqual(first.dependencies, [
			request.dependencies[1],
			request.dependencies[0],
		]);
		assert.deepEqual(first.exportedSymbols, [
			request.exportedSymbols[1],
			request.exportedSymbols[0],
		]);
	} finally {
		await rm(loaded.root, { recursive: true, force: true });
	}
});

test('project emitter uses the production runtime import and import framing', async () => {
	const loaded = await loadEmitter();
	try {
		const result = emit(loaded.module, {
			entryPath: 'src/main.virune',
			modules: [
				{
					sourcePath: 'src/main.virune',
					outputPath: 'dist/main.js',
					preamble: [
						SELFHOST_RUNTIME_IMPORT_LINE,
						"import { value } from './helper.js';",
						"import './side-effect.js';",
					],
					statements: ['export function main() { return value; }'],
					sourceMap: '',
				},
			],
			dependencies: [],
			exportedSymbols: [],
		});
		assert.equal(result.accepted, true);
		assert.deepEqual(result.diagnostics, []);
		assert.equal(
			result.emittedModules[0]?.code,
			[
				BASE_RUNTIME_IMPORT_LINE,
				'',
				'import { value } from "./helper.js";',
				'import "./side-effect.js";',
				'',
				'export function main() { return value; }',
				'',
			].join('\n'),
		);
		assert.doesNotMatch(result.emittedModules[0]?.code ?? '', /Generated by Virune self-host/u);
	} finally {
		await rm(loaded.root, { recursive: true, force: true });
	}
});

test('project emitter fails closed for duplicate outputs, multiline entries, and missing entry', async () => {
	const loaded = await loadEmitter();
	try {
		const result = emit(loaded.module, {
			entryPath: 'src/missing.virune',
			modules: [
				{
					sourcePath: 'src/a.virune',
					outputPath: 'dist/shared.js',
					preamble: [],
					statements: ['line one\nline two'],
					sourceMap: '',
				},
				{
					sourcePath: 'src/b.virune',
					outputPath: 'dist/shared.js',
					preamble: [],
					statements: [],
					sourceMap: '',
				},
			],
			dependencies: [],
			exportedSymbols: [],
		});
		assert.equal(result.accepted, false);
		assert.deepEqual(result.emittedModules, []);
		assert.deepEqual(result.diagnostics.map(item => item.code), ['SHP4006', 'SHP4004', 'SHP4008']);
	} finally {
		await rm(loaded.root, { recursive: true, force: true });
	}
});

test('project emitter rejects dangling and duplicate metadata deterministically', async () => {
	const loaded = await loadEmitter();
	try {
		const modules = [
			{
				sourcePath: 'src/main.virune',
				outputPath: 'dist/main.js',
				preamble: [],
				statements: ['export function main() {}'],
				sourceMap: '',
			},
			{
				sourcePath: 'src/helper.virune',
				outputPath: 'dist/helper.js',
				preamble: [],
				statements: ['export const value = 1;'],
				sourceMap: '',
			},
		];
		const validDependency = {
			modulePath: 'src/main.virune',
			sourceKind: 'virune',
			specifier: './helper.virune',
			resolvedPath: 'src/helper.virune',
			typeOnly: false,
			public: false,
		};
		const dependencies = [
			{
				modulePath: 'src/main.virune',
				sourceKind: 'virune',
				specifier: './unresolved.virune',
				resolvedPath: null,
				typeOnly: false,
				public: false,
			},
			validDependency,
			{
				modulePath: 'src/ghost.virune',
				sourceKind: 'javascript',
				specifier: 'node:fs',
				resolvedPath: null,
				typeOnly: false,
				public: false,
			},
			{
				modulePath: 'src/main.virune',
				sourceKind: 'virune',
				specifier: './missing.virune',
				resolvedPath: 'src/missing.virune',
				typeOnly: false,
				public: false,
			},
			validDependency,
		];
		const validExport = {
			modulePath: 'src/main.virune',
			name: 'main',
			declarationKind: 'FunctionDeclaration',
		};
		const exportedSymbols = [
			validExport,
			{ modulePath: 'src/ghost.virune', name: 'ghost', declarationKind: 'FunctionDeclaration' },
			validExport,
		];
		const first = emit(loaded.module, {
			entryPath: 'src/main.virune',
			modules,
			dependencies,
			exportedSymbols,
		});
		const second = emit(loaded.module, {
			entryPath: 'src/main.virune',
			modules: [...modules].reverse(),
			dependencies: [...dependencies].reverse(),
			exportedSymbols: [...exportedSymbols].reverse(),
		});
		assert.equal(first.accepted, false);
		assert.equal(second.accepted, false);
		assert.deepEqual(first, second);
		assert.deepEqual(first.emittedModules, []);
		assert.deepEqual(first.diagnostics.map(item => item.code), [
			'SHP4009',
			'SHP4012',
			'SHP4010',
			'SHP4010',
			'SHP4011',
			'SHP4013',
		]);
		assert.deepEqual(first.diagnostics.map(item => item.sourcePath), [
			'src/ghost.virune',
			'src/main.virune',
			'src/main.virune',
			'src/main.virune',
			'src/ghost.virune',
			'src/main.virune',
		]);
	} finally {
		await rm(loaded.root, { recursive: true, force: true });
	}
});

function emit(module: EmitterApi, request: unknown): EmitterResult {
	const encoded = module.emitProjectJson(JSON.stringify(request));
	assert.equal(encoded.$tag, 'Ok');
	return JSON.parse(encoded.$values[0]) as EmitterResult;
}

async function loadEmitter(): Promise<{ readonly root: string; readonly module: EmitterApi }> {
	const result = await buildProject(mvpRoot, {
		write: false,
		additionalEntries: ['src/project-emitter.virune'],
	});
	const errors = result.diagnostics.filter(item => item.severity === 'error');
	assert.deepEqual(errors.map(item => `${item.code}:${item.message}`), []);

	await mkdir(temporaryRoot, { recursive: true });
	const root = await mkdtemp(join(temporaryRoot, 'selfhost-project-emitter-'));
	const configuredOutDir = resolve(mvpRoot, 'dist');
	const outputPaths: string[] = [];
	for (const built of result.modules) {
		if (built.output === undefined || built.outputPath === undefined) continue;
		const outputPath = join(root, relative(configuredOutDir, built.outputPath));
		await mkdir(dirname(outputPath), { recursive: true });
		await writeFile(outputPath, built.output.code);
		outputPaths.push(outputPath);
	}
	for (const outputPath of outputPaths.sort()) await execFileAsync(process.execPath, ['--check', outputPath]);
	const moduleUrl = `${pathToFileURL(join(root, 'project-emitter.js')).href}?test=${Date.now()}`;
	return { root, module: await import(moduleUrl) as EmitterApi };
}