import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdir, rm } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildProject } from '../src/project/project.js';
import { snapshotProjectBuild } from '../src/selfhost/bootstrap-artifact-snapshot.js';
import {
	loadBootstrapCompilerCandidate,
	materializeBootstrapCompilerCandidate,
} from '../src/selfhost/bootstrap-execution-probe.js';
import { kernelInputFromProjectBuild } from '../src/selfhost/bootstrap-stage-runner.js';
import {
	compileWithProjectCompilerBoundary,
	hasSelfhostProjectCompilerExports,
	readProjectCompilerCapability,
} from '../src/selfhost/project-compiler-adapter.js';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');
const mvpRoot = join(repositoryRoot, 'selfhost', 'mvp');
const temporaryRoot = join(repositoryRoot, '.test-tmp');
const snapshotOptions = {
	stage: 'stage0' as const,
	compilerVersion: '1.0.0',
	runtimeAbi: '1',
	interopAbi: '1',
	seedSha256: 'e'.repeat(64),
};

type ProjectInput = ReturnType<typeof kernelInputFromProjectBuild>;
type GeneratedCompiler = Awaited<ReturnType<typeof loadBootstrapCompilerCandidate>>;

async function withGeneratedCompiler<T>(
	run: (module: GeneratedCompiler, input: ProjectInput) => T | Promise<T>,
): Promise<T> {
	await mkdir(temporaryRoot, { recursive: true });
	const build = await buildProject(mvpRoot, { write: false });
	const artifact = snapshotProjectBuild(build, snapshotOptions);
	const root = await materializeBootstrapCompilerCandidate(artifact, temporaryRoot);
	try {
		const module = await loadBootstrapCompilerCandidate(root, 'dist/main.js');
		return await run(module, kernelInputFromProjectBuild(build));
	} finally {
		await rm(root, { recursive: true, force: true });
		await rm(temporaryRoot, { recursive: true, force: true });
	}
}

function focusedProjectInput(input: ProjectInput): ProjectInput {
	return {
		...input,
		entryPath: 'src/main.virune',
		sources: [
			{ path: 'src/helper.virune', text: '' },
			{ path: 'src/main.virune', text: '' },
		],
	};
}

function compilerReturning(module: GeneratedCompiler, result: unknown) {
	return {
		...module,
		compileProjectMvp: (_request: string) => ({
			$tag: 'Ok' as const,
			$values: [JSON.stringify(result)] as const,
		}),
	};
}

test('generated compiler exposes deterministic integrated full-language capability', async () => {
	await withGeneratedCompiler((module) => {
		assert.equal(hasSelfhostProjectCompilerExports(module), true);
		const first = readProjectCompilerCapability(module);
		const second = readProjectCompilerCapability(module);
		assert.deepEqual(first, second);
		assert.deepEqual(first, {
			contractVersion: '1',
			ready: true,
			requestSchema: 'virune.selfhost.project-compiler.request.v1',
			resultSchema: 'virune.selfhost.project-compiler.result.v2',
			blockers: [],
		});
	});
});

test('valid empty project flows through parse, link, semantics, lowering, and deterministic emission', async () => {
	await withGeneratedCompiler((module, input) => {
		const projectInput = focusedProjectInput(input);
		const first = compileWithProjectCompilerBoundary(module, projectInput);
		const second = compileWithProjectCompilerBoundary(module, projectInput);
		assert.deepEqual(first, second);
		assert.equal(first.accepted, true);
		assert.deepEqual(first.diagnostics, []);
		assert.deepEqual(first.dependencies, []);
		assert.deepEqual(first.exportedSymbols, []);
		assert.deepEqual(first.emittedModules.map(item => item.outputPath), [
			'.selfhost-output/src/helper.js',
			'.selfhost-output/src/main.js',
		]);
		assert.ok(first.emittedModules.every(item => item.code.startsWith('// Generated by Virune self-host project emitter.\n')));
		assert.ok(first.emittedModules.every(item => item.code.includes("from '@virune/runtime/v2/index.js';")));
		assert.deepEqual(first.stats, {
			parsedModules: 2,
			reusedParsedModules: 0,
			checkedModules: 2,
			reusedCheckedModules: 0,
			emittedModules: 2,
			reusedEmittedModules: 0,
			invalidatedModules: 0,
		});
	});
});

test('Pure Core MVP modules emit canonical exports in project order', async () => {
	await withGeneratedCompiler((module, input) => {
		const projectInput: ProjectInput = {
			...focusedProjectInput(input),
			sources: [
				{
					path: 'src/helper.virune',
					text: 'pub fn helper() -> Int {\n\treturn 1\n}\n',
				},
				{
					path: 'src/main.virune',
					text: 'pub fn main() -> Int {\n\treturn 2\n}\n',
				},
			],
		};
		const result = compileWithProjectCompilerBoundary(module, projectInput);
		assert.equal(result.accepted, true);
		assert.deepEqual(result.diagnostics, []);
		assert.deepEqual(result.exportedSymbols, [
			{ modulePath: 'src/helper.virune', name: 'helper', declarationKind: 'FunctionDeclaration' },
			{ modulePath: 'src/main.virune', name: 'main', declarationKind: 'FunctionDeclaration' },
		]);
		assert.equal(result.emittedModules.length, 2);
		assert.match(result.emittedModules[0]?.code ?? '', /export function helper/u);
		assert.match(result.emittedModules[1]?.code ?? '', /export function main/u);
	});
});

test('malformed project source returns path-aware frontend diagnostics before project linking', async () => {
	await withGeneratedCompiler((module, input) => {
		const projectInput = focusedProjectInput(input);
		const malformedInput: ProjectInput = {
			...projectInput,
			sources: projectInput.sources.map(source => source.path === projectInput.entryPath
				? { ...source, text: 'pub fn broken(' }
				: source),
		};
		const result = compileWithProjectCompilerBoundary(module, malformedInput);
		assert.equal(result.accepted, false);
		assert.equal(result.stats.parsedModules, projectInput.sources.length);
		assert.equal(result.stats.checkedModules, 0);
		assert.equal(result.stats.emittedModules, 0);
		assert.ok(result.diagnostics.length > 0);
		const entryDiagnostic = result.diagnostics.find(item => item.sourcePath === projectInput.entryPath);
		assert.ok(entryDiagnostic);
		assert.match(entryDiagnostic.code, /^L/u);
		assert.equal(entryDiagnostic.severity, 'error');
		assert.ok(entryDiagnostic.span.start.line >= 1);
		assert.ok(entryDiagnostic.span.end.offset >= entryDiagnostic.span.start.offset);
	});
});

test('record-only source lowers as a type-only declaration with stable export metadata', async () => {
	await withGeneratedCompiler((module, input) => {
		const projectInput: ProjectInput = {
			...input,
			entryPath: 'src/main.virune',
			sources: [{
				path: 'src/main.virune',
				text: 'pub record User derives Eq, Debug, Json {\n\tname: String\n}\n',
			}],
		};
		const result = compileWithProjectCompilerBoundary(module, projectInput);
		assert.equal(result.accepted, true);
		assert.deepEqual(result.diagnostics, []);
		assert.equal(result.stats.parsedModules, 1);
		assert.equal(result.stats.checkedModules, 1);
		assert.equal(result.stats.emittedModules, 1);
		assert.deepEqual(result.dependencies, []);
		assert.deepEqual(result.exportedSymbols, [
			{ modulePath: 'src/main.virune', name: 'User', declarationKind: 'RecordDeclaration' },
		]);
		assert.equal(result.emittedModules.length, 1);
		assert.equal(result.emittedModules[0]?.sourcePath, 'src/main.virune');
		assert.doesNotMatch(result.emittedModules[0]?.code ?? '', /record User/u);
	});
});

test('unsorted direct project request fails closed before source parsing', async () => {
	await withGeneratedCompiler((module, input) => {
		if (!hasSelfhostProjectCompilerExports(module)) {
			throw new Error('Generated compiler must export the project compiler boundary');
		}
		const projectInput = focusedProjectInput(input);
		const resultValue = module.compileProjectMvp(JSON.stringify({
			contractVersion: projectInput.contractVersion,
			languageVersion: projectInput.languageVersion,
			platform: projectInput.platform,
			entryPath: projectInput.entryPath,
			sources: [...projectInput.sources]
				.reverse()
				.map(source => ({ path: source.path, text: source.text })),
			emit: projectInput.emit,
		}));
		assert.equal(resultValue.$tag, 'Ok');
		const result = JSON.parse(resultValue.$values[0] as string) as {
			readonly diagnostics: readonly { readonly code: string; readonly sourcePath: string | null }[];
			readonly stats: { readonly parsedModules: number };
		};
		assert.deepEqual(result.diagnostics.map(item => item.code), ['SHP1012']);
		assert.equal(result.diagnostics[0]?.sourcePath, null);
		assert.equal(result.stats.parsedModules, 0);
	});
});

test('legacy count-only result shape remains rejected', async () => {
	await withGeneratedCompiler((module, input) => {
		const legacyShape = {
			...module,
			compileProjectMvp: (_request: string) => ({
				$tag: 'Ok' as const,
				$values: [JSON.stringify({
					contractVersion: '1',
					accepted: false,
					diagnostics: [{ code: 'SHP2000', severity: 'error', message: 'not implemented' }],
					emittedModuleCount: 0,
				})] as const,
			}),
		};
		assert.throws(
			() => compileWithProjectCompilerBoundary(legacyShape, focusedProjectInput(input)),
			/keys must be exactly/u,
		);
	});
});

test('invalid contract data and malformed JSON fail closed', async () => {
	await withGeneratedCompiler((module, input) => {
		if (!hasSelfhostProjectCompilerExports(module)) {
			throw new Error('Generated compiler must export the project compiler boundary');
		}
		const projectInput = focusedProjectInput(input);
		const invalidVersion = module.compileProjectMvp(JSON.stringify({
			contractVersion: '2',
			languageVersion: projectInput.languageVersion,
			platform: projectInput.platform,
			entryPath: projectInput.entryPath,
			sources: projectInput.sources.map(source => ({ path: source.path, text: source.text })),
			emit: projectInput.emit,
		}));
		assert.equal(invalidVersion.$tag, 'Ok');
		const result = JSON.parse(invalidVersion.$values[0] as string) as {
			readonly accepted: boolean;
			readonly diagnostics: readonly {
				readonly code: string;
				readonly sourcePath: string | null;
				readonly notes: readonly string[];
			}[];
			readonly emittedModules: readonly unknown[];
			readonly dependencies: readonly unknown[];
			readonly exportedSymbols: readonly unknown[];
			readonly stats: { readonly parsedModules: number };
		};
		assert.equal(result.accepted, false);
		assert.deepEqual(result.diagnostics.map(item => item.code), ['SHP1001']);
		assert.equal(result.diagnostics[0]?.sourcePath, null);
		assert.deepEqual(result.diagnostics[0]?.notes, []);
		assert.equal(result.stats.parsedModules, 0);
		assert.deepEqual(result.emittedModules, []);
		assert.deepEqual(result.dependencies, []);
		assert.deepEqual(result.exportedSymbols, []);

		const malformed = module.compileProjectMvp('{');
		assert.equal(malformed.$tag, 'Err');
	});
});

test('project result paths cannot escape the request source set', async () => {
	await withGeneratedCompiler((module, input) => {
		const projectInput = focusedProjectInput(input);
		const valid = compileWithProjectCompilerBoundary(module, projectInput);
		const invalidResults = [
			{
				value: {
					...valid,
					emittedModules: valid.emittedModules.map((item, index) => index === 0
						? { ...item, sourcePath: 'src/ghost.virune' }
						: item),
				},
				expected: /\$\.emittedModules sourcePath must identify a request source/u,
			},
			{
				value: {
					...valid,
					dependencies: [{
						modulePath: 'src/ghost.virune',
						sourceKind: 'virune',
						specifier: './helper.virune',
						resolvedPath: 'src/helper.virune',
						typeOnly: false,
						public: false,
					}],
				},
				expected: /\$\.dependencies modulePath must identify a request source/u,
			},
			{
				value: {
					...valid,
					dependencies: [{
						modulePath: 'src/main.virune',
						sourceKind: 'virune',
						specifier: './ghost.virune',
						resolvedPath: 'src/ghost.virune',
						typeOnly: false,
						public: false,
					}],
				},
				expected: /\$\.dependencies resolvedPath must identify a request source/u,
			},
			{
				value: {
					...valid,
					exportedSymbols: [{
						modulePath: 'src/ghost.virune',
						name: 'ghost',
						declarationKind: 'FunctionDeclaration',
					}],
				},
				expected: /\$\.exportedSymbols modulePath must identify a request source/u,
			},
		];
		for (const invalid of invalidResults) {
			assert.throws(
				() => compileWithProjectCompilerBoundary(compilerReturning(module, invalid.value), projectInput),
				invalid.expected,
			);
		}
	});
});

test('accepted project results must report coherent module coverage', async () => {
	await withGeneratedCompiler((module, input) => {
		const projectInput = focusedProjectInput(input);
		const valid = compileWithProjectCompilerBoundary(module, projectInput);
		assert.throws(
			() => compileWithProjectCompilerBoundary(compilerReturning(module, {
				...valid,
				stats: { ...valid.stats, checkedModules: 1 },
			}), projectInput),
			/accepted result must check every request source/u,
		);
		assert.throws(
			() => compileWithProjectCompilerBoundary(compilerReturning(module, {
				...valid,
				stats: { ...valid.stats, checkedModules: 3 },
			}), projectInput),
			/checked and reused checked module counts cannot exceed parsed module counts/u,
		);
		assert.throws(
			() => compileWithProjectCompilerBoundary(compilerReturning(module, {
				...valid,
				stats: { ...valid.stats, invalidatedModules: 3 },
			}), projectInput),
			/invalidatedModules cannot exceed request source count/u,
		);
	});
});
